// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joonduzxxoouzmehasvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvb25kdXp4eG9vdXptZWhhc3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4ODYxNzUsImV4cCI6MjA1MzQ2MjE3NX0.Xg1GmO6U1ZAIeIciu3loo2l8U1d_uBkgVGbE7jtb-oA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);